### PR TITLE
zig msvc toolchain support

### PR DESCRIPTION
**Pull request by jinzhongjia**
Add a macro definition and use `_strdup` instead of `strdup` under msvc

### CODE REVIEW

**Comment by SpikeHD** [comment]
While seemingly unrelated, this PR is required for https://github.com/webui-dev/rust-webui/pull/3 to work. Would love to see this merged!

**Comment by jinzhongjia** [comment]
Hey, @neroist
@hassandraga hasn't appeared in a long time, maybe we should merge these PRs for now?

**Comment by jinzhongjia** [comment]
Now this PR contains the API fix of zig nightly

**Review by fibodevy — APPROVED** [review]

**Comment by jinzhongjia** [comment]
Thx!

**Pull request merged**
