### PR TITLE
Disable linting CI

### PR DESCRIPTION
**Pull request by ttytm**
Disables the lint if that's desired.

I didn't experiences such common linters as issue before in other projects and the tools are available for all platform and usually every editor by default. If there is a configuration issue I might can help. Else feel free to disable 👍

### CODE REVIEW

**Comment by hassandraga** [comment]
No, Actually I was about to ask you how I use the formatter config files. I formatted the code using Clang and Prettier, but the CI always fails for my PR. Can you show me please how? I'm using VSCode.

**Comment by ttytm** [comment]
Sorry about the delay. Gonna respond when getting a free moment to give proper help.

**Comment by hassandraga** [comment]
I found how. I'm working on making the style more readable.
Thank you 👍

**Comment by hassandraga** [comment]
I spent hours trying to make clang-format align the PPs `#ifdef`... In the end, I found that their latest version v18 does not have this feature. The code is really hard to read because of this non-aligned `#ifdef`... so I spent other hours manually formatting the code 🤷‍♂️

Thank you for the CI lint implementation 👍we will restore it when the clang-format includes this feature.

**Pull request closed without merging**
