### PR TITLE
Simplify building examples with Zig

### PR DESCRIPTION
**Pull request by ttytm**
It’s really handy to have the possibility to build with Zig; it provides everything so fast. I’m just getting into using it more now. Thanks for adding it @jinzhongjia .

The changes simplify building the examples. It removes two nesting levels by handling the "unhappy-path" early.

### CODE REVIEW

**Review by jinzhongjia — APPROVED** [review]

**Comment by jinzhongjia** [comment]
To be honest, I don’t recommend continuing to pay attention to version 0.11. The improvement in the build system of 0.12 compared to 0.11 is huge.

**Comment by ttytm** [comment]
Yep, I think too moving with 0.12 and beyond is the way to go. Lets update in the near future.

**Comment by jinzhongjia** [comment]
At present, I have transferred the build code corresponding to 0.12 and zig master branch to zig-webui. The build.zig retained in webui is only to ensure compatibility with 0.11

**Comment by jinzhongjia** [comment]
Currently, zig-webui can also directly package and build dynamic link libraries and static link libraries.

**Pull request merged**
