### PR TITLE
ci: add release step

### PR DESCRIPTION
**Pull request by ttytm**
<em>PR description will be updated</em>

### CODE REVIEW

**Comment by ttytm** [comment]
My time is fairly limited atm :/. I don't think to get the chance to finish it today. But over the weekend it should be done.
I'll test cross compilation for mac m1 and add it as mac release if all works out. When it's finished I'll leave a short description about the release process and mark it as ready for review :+1:.

**Comment by JOTSR** [comment]
LGTM.
Maybe for a next PR but in #138 @AlbertShown discussed to track the generated js files in the repository and I proposed to rather providing them (*.js and xxd outputs) in the release source code archive. What do you think about that and is it possible to simply add these bundle in `build.yml`.

**Comment by ttytm** [comment]
@JOTSR 
Yes it's possible. We build the client in the workflow so we could just add the `webui.js` to the bundle. Lets agree on something in the related PR.

**Comment by ttytm** [comment]
I came to work late on this on despite the weekend so it will take a few days more. Sorry about the delay.

Something positive I can say is that building for m1 macs works. Also I think we can handle the examples nicely and make them generally cleaner. I'll push necessary changes that can stand on their own in separate PRs. So we get step by step to finishing the release CI.

**Comment by AlbertShown** [comment]
@JOTSR You can close the review as done if you think this should be merged.

About the `webui.js` file, there are many solutions. Still, the main goal is to make non-js developers can easily clone and build WebUI without the need to install `dxx`, `esbuild`, `npm` etc... those should be installed and used for TS/JS developers who want to improve/debug the WebUI-JS-Bridge Script.

**Comment by ttytm** [comment]
Probably a little misconception but the PR was marked as draft because it wasn't finished.

**Comment by AlbertShown** [comment]
Opsy!

**Pull request merged**
